CREATE TABLE car (
    id SERIAL PRIMARY KEY, 
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    rent_per_day NUMERIC(10, 2) NOT NULL,
    address TEXT NOT NULL, 
    images TEXT NOT NULL, 
    year INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    power INTEGER NOT NULL,
    mileage INTEGER NOT NULL,
    brand VARCHAR(255) NOT NULL,
    transmission VARCHAR(50) NOT NULL,
    fuel_type VARCHAR(50) NOT NULL,
    seats INTEGER NOT NULL,
    doors INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
